apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    client.knative.dev/user-image: europe-central2-docker.pkg.dev/czk-tools/cloud-run-source-deploy/run-doi-request-test
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  labels:
    cloud.googleapis.com/location: europe-central2
  name: run-doi-request-test
  namespace: '783523983505'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        client.knative.dev/user-image: europe-central2-docker.pkg.dev/czk-tools/cloud-run-source-deploy/run-doi-request-test
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 394.0.0
      name: run-doi-request-test-00006-heg
    spec:
      containerConcurrency: 80
      containers:
      - image: europe-central2-docker.pkg.dev/czk-tools/cloud-run-source-deploy/run-doi-request-test@sha256:460b51a5a21ea9f85993f7c2685f02986ee9e4005e4034a4df4e843ce75cc7de
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        env:
        - name: JIRA_CZK_USER
          valueFrom:
            secretKeyRef:
              key: latest
              name: jira-czk-user
        - name: JIRA_CZK_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: jira-czk-key
      serviceAccountName: 783523983505-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
